### ISSUE TITLE
各产品运行图片

### ISSUE THREAD

**Issue by Anticristum** [mulab/www#33]
就像zhihu.com/app中这样

**Comment by hqythu** [comment]
意思是那种应用截图之类？

**Comment by hqythu** [comment]
这个似乎没解决吧……

**Comment by Anticristum** [comment]
因为没人来领锅啊ORZ

**Comment by zmy** [comment]
可以截图或者YY...

比如Now可以拿 https://www.google.com/landing/now/#cards 的PS
