### ISSUE TITLE
更新gulp-if

### ISSUE THREAD

**Issue by benpigchu** [mulab/www#80]
由于nodejs 6中的v8的一个特性的变化，gulp-if的依赖gulp-match会在nodejs 6中出现bug（ robrich/gulp-match#12 ），导致在gulp的HTML任务中html文件被识别为js文件，build失败。
将gulp-if更新至2.0.1后可以解决这个问题。

**Comment by hqythu** [comment]
make a PR.

better to test compatibility on Node 4, 5, 6
