### ISSUE TITLE
细节调整

### ISSUE THREAD

**Issue by TennyZhuang** [mulab/www#83]
- [x] navbar需要一直显示在顶端
- [x] members的照片鼠标放上去的时候快速变成紫色，不用旋转效果
- [x] about页面的图片用原来的图片，遮罩用css加
- [x] members和“我们由来自不同背景，不同学院的同学们组成”、logo没有对齐
- [x] 把logo旁边的“哪些码代码、赶设计、求涨粉的日日夜夜……“那些字缩小占据一行，白色区域的高度减少

尽快尽可能完成，不好改的就算了 @benpigchu

**Comment by TennyZhuang** [comment]
about 页面的原图

http://7xleha.com1.z0.glb.clouddn.com/FF48B1471548D322CECDB4E53CFC7F07.jpg

**Comment by benpigchu** [comment]
【logo对齐问题似乎在 df5a98f851bd56fa4fd00e94653510491674d0a4 中解决了】

**Comment by TennyZhuang** [comment]
似乎是我下午解决的，你看看剩下的

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.6.23&pv=9.2.1&source=email_footer_2]
On Wed, Sep 14, 2016 at 23:07, Ben Pig Chu <notifications@github.com> wrote:
【logo对齐问题似乎在 df5a98f [https://github.com/mulab/www/commit/df5a98f851bd56fa4fd00e94653510491674d0a4] 中解决了】

**Comment by benpigchu** [comment]
【要是member页面的题头图也有原图就好了（】

**Comment by TennyZhuang** [comment]
@benpigchu members 暂时先这样吧

**Comment by TennyZhuang** [comment]
来一发 PR？

**Comment by benpigchu** [comment]
【PR过了（】

**Comment by TennyZhuang** [comment]
Fixed in #84
