### ISSUE TITLE
Tsinghua Now itunes link

### ISSUE THREAD

**Issue by zmy** [mulab/www#90]
目前指向的是iTUNet

**Comment by SongzhouYang** [comment]
这个应该是后台做的跳转？

**Comment by TennyZhuang** [comment]
nginx后台啊，上层转发到 www.lab.mu，然后这边判断 host 是不是 tunet.lab.mu 来跳转的意思，大概

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.6.23&pv=9.2.1&source=email_footer_2]
On Thu, Sep 22, 2016 at 08:36, Songzhou Yang <notifications@github.com> wrote:
这个应该是后台做的跳转？

**Comment by hqythu** [comment]
那个链接写的本身是 http://tunet.lab.mu/itunes ，当然跑到iTUNet那里去了

**Comment by hqythu** [comment]
now 似乎还没有iTunes的链接，now.lab.mu/itunes.
@cgcgbcbc

**Comment by SongzhouYang** [comment]
now还没有iTunes的链接

**Comment by TennyZhuang** [comment]
先写上吧，等光大大醒了添加？

**Comment by zmy** [comment]
http://now.lab.mu/itunes 可以使用了，尽快替换吧~

**Comment by hqythu** [comment]
@SongzhouYang 加上
